server:
  port: 80
eureka:
  client:
    service-url:
      #访问端口
      defaultZone: http://localhost7001:7001/eureka/,http://localhost7002:7002/eureka/,http://localhost7003:7003/eureka/
    register-with-eureka: true #向Eureka注册自己
  instance:
    instance-id: springcloud-consumer-dept-80 #修改eureka上的默认信息描述
    prefer-ip-address: true # 显示ip
    lease-renewal-interval-in-seconds: 1   # 发送心跳时间间隔
    lease-expiration-duration-in-seconds: 2    # 服务端接收心跳最大间隔时间

spring:
  application:
    name: spring-consumer-dept
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率，介于0-1，1表示全部采集
      probability: 1

