#spring:
#  thymeleaf:
#    prefix: classpath:/static/
#    encoding: utf-8

server:
  servlet:
    context-path: "/ghj"

spring:
  messages:
    basename: "i18n.login"

  mvc:
    format:
      date: yyyy-MM-dd
