server:
  port: 9527

spring:
  main:
    web-application-type: reactive #spring-boot-starter-web会与gateway依赖相互矛盾。
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes: # 可以配置多个， 这里只配置了一个， 再加的话就是 -id下面的再写一套
        - id: dept_8001 #路由ID，要唯一
          #uri: http:localhost:8001 匹配后提供服务的路径
          uri: lb://spring-provider-dept #匹配后提供服务的路由地址， lb就是LoadBalance的缩写， 就可以实现负载均衡了；
          predicates:
            - Path=/dept/** #断言， 路径相匹配的进行路由
            # - After=2022-06-15T17:23:06.302617600+08:00[Asia/Shanghai] #匹配改时间之后的， 进行路由
            - Method=GET
          filters:
            - AddRequestHeader=X-Request-red, blue
      discovery:
        locator:
          enabled: true #开启从服务中心动态创建路由功能， 理由服务名进行路由


eureka:
  client:
    service-url:
      defaultZone: http://localhost7001:7001/eureka/,http://localhost7002:7002/eureka/,http://localhost7003:7003/eureka/
      fetch-registry: true # 要不要去注册中心获取其他服务的地址
      register-with-eureka: true

  instance:
    instance-id: gateway9527
    prefer-ip-address: true


