server:
  port: 8081


debug: true
---
server:
  port: 8082
spring:
  config:
    activate:
      on-profile: dev
---
server:
  port: 8083
spring:
  config:
    activate:
      on-profile: test

---
server:
  port: 8083
spring:
  config:
    activate:
      on-profile: main