server:
  port: 8803
spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ghjlj.cn
                port: 5672
                username: admin
                password: admin
      bindings:
        input:
          destination: SpringCloud-Stream
          content-type: application/json
          binder: {defaultRabbit}
          group: ghjlj
#eureka的配置， 服务注册到什么地方
eureka:
  client:
    service-url:
      defaultZone: http://localhost7001:7001/eureka/
  instance:
    instance-id: springcloud-stream-consumer-8803 #修改eureka上的默认信息描述
    prefer-ip-address: true # 显示ip
    lease-renewal-interval-in-seconds: 1   # 发送心跳时间间隔
    lease-expiration-duration-in-seconds: 2    # 服务端接收心跳最大间隔时间

