
people:
  name: ghj${random.uuid}
  age: ${random.int}
  map: {k1: v1,k2: v2}
  hello: xx
  list:
    - a
    - b
    - c
  dog:
    name: ${people.hello:ak}_旺财
    age: 3

dog:
  dog-name: 旺财
  age: 12